### Endpoint de teste
Post http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Astro Dev",
    "email": "astrodev@gmail.com",
    "password": "123456"
}

###

POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "astrodev@gmail.com",
    "password": "123456"
}